#!/usr/bin/env python

import sys
import os.path

# Check installation
if os.path.isfile("./src/tef_search"):

    # Configuration import
    from src.tef import *

    if __name__ == "__main__":
        main(sys.argv)

else:
    print "Error: incomplete TEF2 installation: 'tef_search' binary not found in ./src/"
    print "    Please read INSTALL.txt"
